# Generated by Django 4.0.5 on 2022-06-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='products',
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='type',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='date',
            field=models.IntegerField(),
        ),
    ]
